services:

  backend:
    build: ./backend/simpleapi
    container_name: simpleapi
    networks:
      - app-network
      - frontend-network

    depends_on:
      - database
    restart: unless-stopped

  database:
    build: ./Database
    container_name: postgre-db
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: usr
      POSTGRESS_PASSWORD : pwd
    volumes:
      - postgres-data:/var/lib/postgresql/data

    networks:
      - app-network
    restart: unless-stopped

  httpd:
    build: ./httpd
    container_name: httpd
    ports:
      - "80:80"
    networks:
      - frontend-network
    depends_on:
      - backend
    restart: unless-stopped

networks:
  app-network:
  frontend-network:

volumes:
  postgres-data:
