#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/app


- name: Run Spring Boot API
  community.docker.docker_container:
    name: simpleapi
    image: "{{ app_image }}"
    pull: always
    state: started
    restart_policy: unless-stopped
    networks:
     - name: app-network
       aliases:
        - backend
    env:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-db:5432/{{ db_name }}"
      SPRING_DATASOURCE_USERNAME: "{{ db_user }}"
      SPRING_DATASOURCE_PASSWORD: "{{ db_password }}"
